package com.example.aquawatch.ui

import androidx.compose.runtime.compositionLocalOf
import com.example.aquawatch.data.AppLanguage

val LocalAppLanguage = compositionLocalOf { AppLanguage.English }

data class AppCopy(
    val welcomeTitle: String,
    val welcomeSubtitle: String,
    val start: String,
    val authSubtitle: String,
    val login: String,
    val signUp: String,
    val welcomeBack: String,
    val signInSubtitle: String,
    val email: String,
    val password: String,
    val forgotPassword: String,
    val signIn: String,
    val createAccount: String,
    val createAccountSubtitle: String,
    val fullName: String,
    val confirmPassword: String,
    val terms: String,
    val dashboard: String,
    val dashboardSubtitle: String,
    val recentAlerts: String,
    val noRecentAlerts: String,
    val noRecentAlertsMessage: String,
    val viewAllAlerts: String,
    val weatherForecast: String,
    val fiveDayForecast: String,
    val map: String,
    val showMyLocation: String,
    val enableLocation: String,
    val monitoringDetails: String,
    val coverage: String,
    val devices: String,
    val activeDevices: String,
    val radius: String,
    val alerts: String,
    val alertsSubtitle: String,
    val noActiveAlerts: String,
    val noActiveAlertsMessage: String,
    val devicesSubtitle: String,
    val noDevices: String,
    val noDevicesMessage: String,
    val monitoringArea: String,
    val monitoringAreaSubtitle: String,
    val areaName: String,
    val areaPhoto: String,
    val addPhoto: String,
    val changePhoto: String,
    val searchPlace: String,
    val searchTypedLocation: String,
    val useGpsLocation: String,
    val saveMonitoringArea: String,
    val tapMapPin: String
)

fun appCopy(language: AppLanguage): AppCopy = when (language) {
    AppLanguage.English -> AppCopy(
        welcomeTitle = "WATCH THE COAST\nBEFORE RISK RISES",
        welcomeSubtitle = "Track weather, monitor devices, review alerts, and open the live map from one modern dashboard.",
        start = "Let's start",
        authSubtitle = "Secure access for coastal monitoring teams",
        login = "Login",
        signUp = "Sign Up",
        welcomeBack = "Welcome back",
        signInSubtitle = "Sign in to continue monitoring live coastal activity.",
        email = "Email Address",
        password = "Password",
        forgotPassword = "Forgot password?",
        signIn = "Sign In",
        createAccount = "Create account",
        createAccountSubtitle = "Register a responder profile for your monitoring station.",
        fullName = "Full Name",
        confirmPassword = "Confirm Password",
        terms = "I agree to Terms and Privacy Policy",
        dashboard = "Dashboard",
        dashboardSubtitle = "Coastal Monitoring Status",
        recentAlerts = "Recent Alerts",
        noRecentAlerts = "No recent alerts",
        noRecentAlertsMessage = "New incidents will appear here when reported.",
        viewAllAlerts = "View All Alerts",
        weatherForecast = "Weather Forecast",
        fiveDayForecast = "5-Day Forecast",
        map = "Map",
        showMyLocation = "Show My Location",
        enableLocation = "Enable Location",
        monitoringDetails = "Monitoring area details",
        coverage = "Coverage",
        devices = "Devices",
        activeDevices = "Active Devices",
        radius = "Radius",
        alerts = "Alerts",
        alertsSubtitle = "Monitor coastal incidents and warnings",
        noActiveAlerts = "No active alerts",
        noActiveAlertsMessage = "New coastal incidents and warnings will appear here.",
        devicesSubtitle = "Manage tracking devices",
        noDevices = "No devices registered",
        noDevicesMessage = "Tap the add button to register a real tracking device.",
        monitoringArea = "Monitoring Area",
        monitoringAreaSubtitle = "Pin the coastal zone your team will watch first.",
        areaName = "Monitoring area name",
        areaPhoto = "Area photo",
        addPhoto = "Add Picture",
        changePhoto = "Change Picture",
        searchPlace = "Search address or place",
        searchTypedLocation = "Search Typed Location",
        useGpsLocation = "Use My GPS Location",
        saveMonitoringArea = "Save Monitoring Area",
        tapMapPin = "Tap map to drop pin"
    )
    AppLanguage.Filipino -> AppCopy(
        welcomeTitle = "BANTAYAN ANG BAYBAYIN\nBAGO TUMAAS ANG RISK",
        welcomeSubtitle = "Subaybayan ang panahon, devices, alerto, at live map mula sa modernong dashboard.",
        start = "Magsimula",
        authSubtitle = "Secure access para sa coastal monitoring teams",
        login = "Login",
        signUp = "Sign Up",
        welcomeBack = "Maligayang balik",
        signInSubtitle = "Mag-sign in para ipagpatuloy ang coastal monitoring.",
        email = "Email Address",
        password = "Password",
        forgotPassword = "Nakalimutan ang password?",
        signIn = "Sign In",
        createAccount = "Gumawa ng account",
        createAccountSubtitle = "Magrehistro ng responder profile para sa monitoring station.",
        fullName = "Buong Pangalan",
        confirmPassword = "Kumpirmahin ang Password",
        terms = "Sumasang-ayon ako sa Terms at Privacy Policy",
        dashboard = "Dashboard",
        dashboardSubtitle = "Status ng Coastal Monitoring",
        recentAlerts = "Recent Alerts",
        noRecentAlerts = "Walang bagong alerto",
        noRecentAlertsMessage = "Lalabas dito ang bagong insidente kapag nai-report.",
        viewAllAlerts = "Tingnan Lahat ng Alerto",
        weatherForecast = "Weather Forecast",
        fiveDayForecast = "5-Day Forecast",
        map = "Mapa",
        showMyLocation = "Ipakita Lokasyon Ko",
        enableLocation = "I-enable ang Lokasyon",
        monitoringDetails = "Detalye ng monitoring area",
        coverage = "Sakop",
        devices = "Devices",
        activeDevices = "Active Devices",
        radius = "Radius",
        alerts = "Mga Alerto",
        alertsSubtitle = "Subaybayan ang coastal incidents at warnings",
        noActiveAlerts = "Walang active alerts",
        noActiveAlertsMessage = "Lalabas dito ang bagong coastal incidents at warnings.",
        devicesSubtitle = "Pamahalaan ang tracking devices",
        noDevices = "Walang registered devices",
        noDevicesMessage = "Pindutin ang add button para mag-register ng tunay na tracking device.",
        monitoringArea = "Monitoring Area",
        monitoringAreaSubtitle = "I-pin ang coastal zone na unang babantayan ng team.",
        areaName = "Pangalan ng monitoring area",
        areaPhoto = "Larawan ng area",
        addPhoto = "Magdagdag ng Larawan",
        changePhoto = "Palitan ang Larawan",
        searchPlace = "Maghanap ng address o lugar",
        searchTypedLocation = "Hanapin ang Tinype na Lokasyon",
        useGpsLocation = "Gamitin GPS Lokasyon Ko",
        saveMonitoringArea = "I-save ang Monitoring Area",
        tapMapPin = "Tap sa mapa para maglagay ng pin"
    )
    AppLanguage.Cebuano -> AppCopy(
        welcomeTitle = "BANTAYI ANG BAYBAYON\nSA DILI PA MOTAAS ANG RISK",
        welcomeSubtitle = "Subaya ang panahon, devices, alerto, ug live map gikan sa modernong dashboard.",
        start = "Sugdi",
        authSubtitle = "Secure access para sa coastal monitoring teams",
        login = "Login",
        signUp = "Sign Up",
        welcomeBack = "Maayong pagbalik",
        signInSubtitle = "Sign in aron ipadayon ang coastal monitoring.",
        email = "Email Address",
        password = "Password",
        forgotPassword = "Nakalimot sa password?",
        signIn = "Sign In",
        createAccount = "Himo og account",
        createAccountSubtitle = "I-register ang responder profile para sa monitoring station.",
        fullName = "Tibuok Ngalan",
        confirmPassword = "Kumpirmaha ang Password",
        terms = "Miuyon ko sa Terms ug Privacy Policy",
        dashboard = "Dashboard",
        dashboardSubtitle = "Status sa Coastal Monitoring",
        recentAlerts = "Recent Alerts",
        noRecentAlerts = "Walay bag-ong alerto",
        noRecentAlertsMessage = "Mogawas dinhi ang bag-ong insidente kung ma-report.",
        viewAllAlerts = "Tan-awa Tanan Alerto",
        weatherForecast = "Weather Forecast",
        fiveDayForecast = "5-Day Forecast",
        map = "Mapa",
        showMyLocation = "Ipakita Akong Lokasyon",
        enableLocation = "I-enable ang Lokasyon",
        monitoringDetails = "Detalye sa monitoring area",
        coverage = "Sakop",
        devices = "Devices",
        activeDevices = "Active Devices",
        radius = "Radius",
        alerts = "Mga Alerto",
        alertsSubtitle = "Subaya ang coastal incidents ug warnings",
        noActiveAlerts = "Walay active alerts",
        noActiveAlertsMessage = "Mogawas dinhi ang bag-ong coastal incidents ug warnings.",
        devicesSubtitle = "Dumala sa tracking devices",
        noDevices = "Walay registered devices",
        noDevicesMessage = "Pislita ang add button aron mag-register og tracking device.",
        monitoringArea = "Monitoring Area",
        monitoringAreaSubtitle = "I-pin ang coastal zone nga bantayan una sa team.",
        areaName = "Ngalan sa monitoring area",
        areaPhoto = "Litrato sa area",
        addPhoto = "Dugang Litrato",
        changePhoto = "Ilisi ang Litrato",
        searchPlace = "Pangitaa ang address o lugar",
        searchTypedLocation = "Pangitaa ang Gi-type nga Lokasyon",
        useGpsLocation = "Gamita Akong GPS Lokasyon",
        saveMonitoringArea = "I-save ang Monitoring Area",
        tapMapPin = "Tap sa mapa aron magbutang og pin"
    )
}
