# Generated by Django 6.0.3 on 2026-06-22 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('time', models.CharField(max_length=64)),
                ('severity', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('serial', models.CharField(max_length=128)),
                ('sim', models.CharField(blank=True, max_length=64)),
                ('owner', models.CharField(blank=True, max_length=128)),
                ('vessel', models.CharField(blank=True, max_length=128)),
                ('registration', models.CharField(blank=True, max_length=128)),
                ('contact', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(default='Active', max_length=64)),
                ('last_location', models.CharField(blank=True, max_length=128)),
                ('last_updated', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Quiapo District Coast Watch', max_length=128)),
                ('latitude', models.FloatField(default=14.5995)),
                ('longitude', models.FloatField(default=120.9842)),
                ('image_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('severity', models.CharField(max_length=64)),
                ('time', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Coastal responder', max_length=128)),
                ('station', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('dark_mode', models.BooleanField(default=True)),
                ('language', models.CharField(default='English', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
